global:
  proxy:
    privileged: false
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

pilot:
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"

cni:
  enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"

sidecarInjectorWebhook:
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
