namespace: go-test

replicaCount: 1

image:
  repository: gcr.io/poetic-orb-430304-r9/go-test
  tag: v1.0.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8200

secret:
  name: go-test-secret

ingress:
  enabled: true

resources:
  limits:
    cpu: "500m"
    memory: "1Gi"
  requests:
    cpu: "250m"
    memory: "512Mi"
