namespace: go-test

replicaCount: 1

image1:
  repository: gcr.io/poetic-orb-430304-r9/go-test-server1
  tag: v1.1.3
  pullPolicy: IfNotPresent

image2:
  repository: gcr.io/poetic-orb-430304-r9/go-test-server2
  tag: v1.1.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8200

secret:
  name: go-test-secret

ingress:
  enabled: true

resources:
  limits:
    cpu: "50m"
    memory: "64Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
