namespace: go-test

replicaCount: 1

image:
  repository: gcr.io/poetic-orb-430304-r9/go-test
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

secret:
  name: go-test-secret

ingress:
  enabled: true
  host: your-app.example.com

resources:
  limits:
    cpu: "0.5"
    memory: "256Mi"
  requests:
    cpu: "0.25"
    memory: "128Mi"
