apiVersion: v1
kind: Service
metadata:
  name: {{  .Release.Name  }}-server1
  namespace: {{  .Values.namespace  }}
spec:
  selector:
    app: {{  .Release.Name  }}-server1
  ports:
    - protocol: TCP
      port: {{  .Values.service.port }}
      targetPort: {{  .Values.service.targetPort  }}
  type: {{  .Values.service.type  }}
