# deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-server
  namespace: go-test
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: go-test-server
  template:
    metadata:
      labels:
        app: go-test-server
    spec:
      containers:
        - name: go-test-server
          image: gcr.io/poetic-orb-430304-r9/go-test:1.0.0 # Replace with your image (e.g., gcr.io/your-project/go-test-server)
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.25"
              memory: "128Mi"
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
