name: Build and Push to GCP

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server1:${{ github.ref_name }} -f server1/Dockerfile
          docker tag gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server1:${{ github.ref_name }} gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server1:latest

          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server2:${{ github.ref_name }} -f server2/Dockerfile
          docker tag gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server2:${{ github.ref_name }} gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server2:latest

      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server1:${{ github.ref_name }}
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server1:latest
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server2:${{ github.ref_name }}
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/go-test-server2:latest
