name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags (e.g., v1.0.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-test:${{ github.ref_name }} .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go-test:latest .

      # Push the Docker image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/go-test:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/go-test:latest
